services:
    redis:
      networks:
        - app_network
      image: redis:latest
      ports:
        - 6379:6379

    db:
      networks:
        - app_network
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: onepoint_test_technique
        POSTGRES_USER: postgres
        PGUSER: postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 3s
        timeout: 5s
        retries: 5

    app:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          NODE_ENV: production
      restart: always
      ports:
        - 3000:3000
      env_file:
        - .env.prod
      depends_on:
        db:
          condition: service_healthy
      command: ["npm", "run", "start:prod"]
      networks:
        - app_network

networks:
  app_network:
    driver: bridge
